### ISSUE TITLE
Wrong code given Build an Airbnb dApp on Fuel Network course for property_state

### ISSUE THREAD

**Issue by DeeKay02** [0xmetaschool/Learning-Projects#468]
The same code has been repeated here where the code of property.sw has been given again for property_state.sw.

The error is in the **Create the Property Library** section under **Start Writing the Sway DApp** module.

![image](https://github.com/0xmetaschool/Learning-Projects/assets/48171972/254079c5-c036-41bc-870c-16054bba2696)

**Comment by snehaweb3kid** [comment]
It has been resolved.
