### ISSUE TITLE
Clarify purpose of setTransactionInProgress in rock-paper-scissors-aptos-dapp

### ISSUE THREAD

**Issue by subhajitroycode** [0xmetaschool/Learning-Projects#653]
I noticed that `setTransactionInProgress` is set but never utilized. The React state is never defined and that's why it's unnecessarily making the code break. 

Could someone explain the intention behind this or confirm if it's redundant and can be removed?

![image](https://github.com/user-attachments/assets/f5d0b830-eb9a-436e-b14a-a594aee305f6)

**Comment by Ash20pk** [comment]
We have added this in case a user wants to add some loading animations in the future, they can use this state variable as a trigger

**Comment by subhajitroycode** [comment]
Uh ok thank you
